#python3 plot_rotational_propagator_linear_rotor.py
#python3 GetFiguresForPIGS.py
#python3 get-figure-rotational-propagator.py
#python get_figure_dipole_dipole_interaction_potential_function.py
python get_raw_data_for_dipole_dipole_interaction_potential_function.py
