#Final Figures obtained from with ratio trick
#cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-Entropy-vs-beta-fixed-tau0.005Kinv-Blocks20000-Passes100-System2HF-preskip10000-postskip0-SWAPTOUNSWAP-aForPPT.eps ../pCloud\ Sync/presentation/Fig_N2_S2_vs_beta.eps
#cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-gFactor2.0-Entropy-vs-tau-fixed-beta0.2Kinv-Blocks20000-Passes100-System2HF-preskip10000-postskip0-SWAPTOUNSWAP.eps ../pCloud\ Sync/presentation/Fig_N2_S2_vs_tau.eps
#cp /Users/tsahoo/ResultsOfENT/ENT-Ratio-Trick-RotDOFs-Rpt10.05Angstrom-Entropy-vs-beta-fixed-tau0.02Kinv-Blocks20000-Passes100-System16HF-preskip10000-postskip0-SWAPTOUNSWAP-aForPPT.eps ../pCloud\ Sync/presentation/Fig_N2_S2_vs_beta.eps
#cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-Entropy-vs-gFactor-of-HF-fixed-beta0.2Kinv-Blocks20000-Passes100-preskip10000-postskip0-SWAPTOUNSWAP-Fit-a.eps ../pCloud\ Sync/presentation/Fig_N2_S2_vs_g.eps
#cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-Entropy-vs-gFactor-of-HF-fixed-beta0.2Kinv-Blocks20000-Passes100-preskip10000-postskip0-SWAPTOUNSWAP-Fit-b.eps ../pCloud\ Sync/presentation/Fig_N4_S2_vs_g.eps
#cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-Entropy-vs-gFactor-of-HF-fixed-beta0.2Kinv-Blocks20000-Passes100-preskip10000-postskip0-SWAPTOUNSWAP-Fit-c.eps ../pCloud\ Sync/presentation/Fig_N8_S2_vs_g.eps
#cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-Entropy-vs-gFactor-of-HF-fixed-beta0.2Kinv-Blocks20000-Passes100-preskip10000-postskip0-SWAPTOUNSWAP-Fit-d.eps ../pCloud\ Sync/presentation/Fig_N16_S2_vs_g.eps
#cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-Entropy-vs-gFactor-of-HF-fixed-beta0.2Kinv-Blocks20000-Passes100-preskip10000-postskip0-SWAPTOUNSWAP-Fit-e.eps ../pCloud\ Sync/presentation/Fig_N32_S2_vs_g.eps
cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-Entropy-vs-gFactor-of-8HF-fixed-beta0.2Kinv-Blocks20000-Passes100-preskip10000-postskip0-Fit-COMBINE-c-ppt.eps /Users/tsahoo/pCloud\ Sync/presentation/ResultsOfENT/Fig_N8_S2_vs_g_BP_and_SU_compare.eps
cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-Entropy-vs-gFactor-of-4HF-fixed-beta0.2Kinv-Blocks20000-Passes100-preskip10000-postskip0-Fit-COMBINE-b-ppt.eps /Users/tsahoo/pCloud\ Sync/presentation/ResultsOfENT/Fig_N4_S2_vs_g_BP_and_SU_compare.eps
cp /Users/tsahoo/ResultsOfENT/ENT-RotDOFs-Rpt10.05Angstrom-Entropy-vs-gFactor-of-2HF-fixed-beta0.2Kinv-Blocks20000-Passes100-preskip10000-postskip0-Fit-COMBINE-a-ppt.eps /Users/tsahoo/pCloud\ Sync/presentation/ResultsOfENT/Fig_N2_S2_vs_g_BP_and_SU_compare.eps
